# Generated by Django 4.2.16 on 2026-07-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_step34_medical_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
