# Generated by Django 4.2.16 on 2026-08-21 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("care_request_create", "Care request create"),
                            ("message_send", "Message send"),
                            ("payment_confirm", "Payment confirm"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "scope", "-created_at"], name="idempo_user_scope_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="idempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("user", "scope", "key"), name="common_idempotency_user_scope_key_uniq"
            ),
        ),
    ]
