# Generated by Django 4.2.16 on 2026-07-18 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_text", models.TextField()),
                ("condition", models.CharField(blank=True, default="", max_length=120)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Sinhala", "Sinhala"),
                            ("Tamil", "Tamil"),
                            ("English", "English"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "care_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("critical", "Critical"),
                        ],
                        default="routine",
                        max_length=16,
                    ),
                ),
                ("source", models.CharField(default="stub", max_length=16)),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-ts",),
            },
        ),
    ]
