# Generated by Django 4.2.16 on 2026-07-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceintent',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
