# Generated by Django 4.2.16 on 2026-07-20 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0003_caregiver_city_available'),
        ('voice', '0002_voiceintent_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, default='', max_length=16)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('intent_chips', models.JSONField(blank=True, default=dict)),
                ('route_history', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('turns', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_match_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue_sessions', to='matching.matchrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'active', '-updated_at'], name='dlg_user_active_idx')],
            },
        ),
    ]
