# Generated by Django 4.2.16 on 2026-07-21 12:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0010_step28_care_request_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_catalog_models_step29'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='awaiting_payment', max_length=20)),
                ('days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('subtotal_lkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_lkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='matching.carerequest')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('package', 'Care package'), ('addon', 'Add-on')], max_length=16)),
                ('catalog_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('unit_price_lkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total_lkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalog.order')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['patient', 'status', '-created_at'], name='order_pt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['care_request', 'status'], name='order_cr_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'awaiting_payment')), fields=('care_request',), name='unique_awaiting_payment_order_per_request'),
        ),
    ]
