# Generated by Django 4.2.16 on 2026-07-21 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_step30_checkout_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock (dev)'), ('payhere', 'PayHere')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('requires_payment', 'Requires payment'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='requires_payment', max_length=20)),
                ('amount_lkr', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('provider_intent_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('client_payload', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='catalog.order')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['order', 'status', '-created_at'], name='pi_order_status_idx'), models.Index(fields=['patient', '-created_at'], name='pi_patient_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requires_payment', 'processing'])), fields=('order',), name='unique_open_payment_intent_per_order'),
        ),
    ]
