# Generated by Django 4.2.16 on 2026-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_step31_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
