# Generated by Django 4.2.16 on 2026-07-19 05:47

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.TextField()),
                ("condition", models.CharField(blank=True, default="", max_length=120)),
                ("language", models.CharField(blank=True, default="", max_length=16)),
                ("care_level", models.CharField(blank=True, default="", max_length=16)),
                ("emergency", models.BooleanField(default=False)),
                (
                    "weights",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), default=list, size=4
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.FloatField()),
                ("cbf", models.FloatField()),
                ("cf", models.FloatField()),
                ("geo", models.FloatField()),
                ("trust", models.FloatField()),
                ("explanation", models.CharField(max_length=255)),
                ("distance_m", models.FloatField(blank=True, null=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_hits",
                        to="matching.caregiverprofile",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="matching.matchrun",
                    ),
                ),
            ],
            options={
                "ordering": ("run", "rank"),
                "unique_together": {("run", "rank")},
            },
        ),
    ]
