# Generated by Django 4.2.16 on 2026-07-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matchrun_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
