# Generated by Django 4.2.16 on 2026-07-20 08:00

import django.core.validators
from django.db import migrations, models


def approve_existing_caregivers(apps, schema_editor):
    CaregiverProfile = apps.get_model("matching", "CaregiverProfile")
    CaregiverProfile.objects.update(is_approved=True, is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0005_patient_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="caregiverprofile",
            name="certification_docs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="nic_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="service_radius_km",
            field=models.FloatField(
                default=25.0,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(200.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="caregiverprofile",
            name="years_experience",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="caregiverprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_caregivers, migrations.RunPython.noop),
    ]
