# Generated by Django 4.2.16 on 2026-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_care_relationship_step24'),
    ]

    operations = [
        migrations.AddField(
            model_name='carerelationship',
            name='end_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='carerelationship',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddConstraint(
            model_name='carerelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'active')), fields=('patient',), name='unique_primary_active_care_relationship'),
        ),
    ]
