# Generated by Django 4.2.16 on 2026-07-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_step42_reviews_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Colombo', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='matching.caregiverprofile')),
            ],
            options={
                'ordering': ('weekday', 'start_time'),
                'indexes': [models.Index(fields=['caregiver', 'is_active', 'weekday', 'start_time'], name='cg_slot_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='caregiveravailabilityslot',
            constraint=models.UniqueConstraint(fields=('caregiver', 'weekday', 'start_time', 'end_time'), name='uniq_cg_slot_window'),
        ),
    ]
