# Generated by Django 4.2.16 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0015_step22d_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("request", "Request"),
                    ("accept", "Accept"),
                    ("complete", "Complete"),
                    ("rate", "Rate"),
                    ("reject", "Reject"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]
