# Generated by Django 4.2.16 on 2026-08-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_step79_matchrun_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cf', 'Collaborative filtering (ALS)'), ('faiss', 'FAISS caregiver index'), ('slot_classifier', 'Offline slot classifier')], db_index=True, max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('trained_at', models.DateTimeField()),
                ('rows_trained_on', models.PositiveIntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-trained_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('kind', 'version'), name='matching_modelversion_kind_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('kind',), name='matching_modelversion_one_active_per_kind'),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='cf_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cf_match_runs', to='matching.modelversion'),
        ),
        migrations.AddField(
            model_name='matchrun',
            name='faiss_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faiss_match_runs', to='matching.modelversion'),
        ),
    ]
