# Generated by Django 5.x for Step 100

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0018_step88_model_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchresult",
            name="was_exploratory",
            field=models.BooleanField(default=False),
        ),
    ]
