# Generated by Django 4.2.16 on 2026-07-18 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view_health', 'View patient health data'), ('grant_consent', 'Grant processing consent'), ('revoke_consent', 'Revoke processing consent'), ('login', 'User login')], max_length=64)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for system).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-ts',),
                'indexes': [models.Index(fields=['action', '-ts'], name='audit_action_ts_idx'), models.Index(fields=['actor', '-ts'], name='audit_actor_ts_idx')],
            },
        ),
    ]
