# Generated by Django 4.2.16 on 2026-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_care_relationship_step24'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view_health', 'View patient health data'), ('view_caregiver', 'View caregiver public profile'), ('grant_consent', 'Grant processing consent'), ('revoke_consent', 'Revoke processing consent'), ('login', 'User login'), ('create_care_request', 'Patient created care request'), ('cancel_care_request', 'Patient cancelled care request'), ('accept_care_request', 'Caregiver accepted care request'), ('reject_care_request', 'Caregiver rejected care request'), ('activate_care_relationship', 'Care relationship activated'), ('end_care_relationship', 'Care relationship ended')], max_length=64),
        ),
    ]
