# Generated by Django 4.2.16 on 2026-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_step31_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view_health', 'View patient health data'), ('view_caregiver', 'View caregiver public profile'), ('grant_consent', 'Grant processing consent'), ('revoke_consent', 'Revoke processing consent'), ('login', 'User login'), ('create_care_request', 'Patient created care request'), ('cancel_care_request', 'Patient cancelled care request'), ('accept_care_request', 'Caregiver accepted care request'), ('reject_care_request', 'Caregiver rejected care request'), ('activate_care_relationship', 'Care relationship activated'), ('end_care_relationship', 'Care relationship ended'), ('create_order', 'Patient created checkout order'), ('create_payment_intent', 'Patient created payment intent'), ('confirm_payment', 'Payment confirmed (mock or webhook)'), ('payment_webhook', 'Payment provider webhook received'), ('receipt_sent', 'Payment receipt emailed to patient')], max_length=64),
        ),
    ]
