# Generated by Django 4.2.16 on 2026-07-22 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_step33_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view_health', 'View patient health data'), ('view_caregiver', 'View caregiver public profile'), ('grant_consent', 'Grant processing consent'), ('revoke_consent', 'Revoke processing consent'), ('login', 'User login'), ('create_care_request', 'Patient created care request'), ('cancel_care_request', 'Patient cancelled care request'), ('accept_care_request', 'Caregiver accepted care request'), ('reject_care_request', 'Caregiver rejected care request'), ('activate_care_relationship', 'Care relationship activated'), ('end_care_relationship', 'Care relationship ended'), ('create_order', 'Patient created checkout order'), ('create_payment_intent', 'Patient created payment intent'), ('confirm_payment', 'Payment confirmed (mock or webhook)'), ('payment_webhook', 'Payment provider webhook received'), ('receipt_sent', 'Payment receipt emailed to patient'), ('create_medical_record', 'Patient created medical record'), ('update_medical_record', 'Patient updated medical record'), ('delete_medical_record', 'Patient soft-deleted medical record')], max_length=64),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
