# Generated by Django 4.2.16 on 2026-07-28 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_step41_web_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification service')], default='fcm', max_length=16)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('app_version', models.CharField(blank=True, default='', max_length=64)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user', 'enabled', '-updated_at'], name='mpd_user_enabled_ts_idx')],
            },
        ),
    ]
