# Generated by Django 4.2.16 on 2026-07-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('heart_rate', 'Heart rate'), ('blood_glucose', 'Blood glucose'), ('spo2', 'SpO2')], db_index=True, max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=24)),
                ('source', models.CharField(blank=True, default='manual', max_length=64)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['patient', 'kind', '-recorded_at'], name='hm_patient_kind_ts_idx'), models.Index(fields=['kind', '-recorded_at'], name='hm_kind_ts_idx')],
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                PERFORM create_hypertable(
                    'health_monitoring_healthmetric',
                    'recorded_at',
                    if_not_exists => TRUE
                );
            EXCEPTION
                WHEN undefined_function THEN
                    NULL;
                WHEN OTHERS THEN
                    -- Keep migration portable if hypertable conversion is blocked by
                    -- local constraints; raw table still works for tests/dev.
                    NULL;
            END$$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
