# Generated by Django 4.2.16 on 2026-07-28 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_monitoring', '0001_step45_health_metric_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('health_critical', 'Health critical')], db_index=True, default='health_critical', max_length=32)),
                ('kind', models.CharField(choices=[('heart_rate', 'Heart rate'), ('blood_glucose', 'Blood glucose'), ('spo2', 'SpO2')], db_index=True, max_length=32)),
                ('rule_key', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(blank=True, default='critical', max_length=24)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField(db_index=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['patient', 'event_type', '-created_at'], name='he_patient_type_ts_idx'), models.Index(fields=['kind', 'rule_key', '-created_at'], name='he_kind_rule_ts_idx')],
            },
        ),
    ]
