# Generated by Django 4.2.16 on 2026-07-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0011_step42_reviews_moderation'),
        ('health_monitoring', '0002_step46_health_critical_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthevent',
            name='handled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='healthevent',
            name='rematch_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_events', to='matching.matchrun'),
        ),
    ]
